server:
  port: 8080
  
spring:
  application:
    name: auth-server
    
security:
  user:
    password: password
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    status-page-url-path: /info
    health-check-url-path: /health
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
